### ISSUE TITLE
Ubuntu packaging

### ISSUE THREAD

**Issue by micheelengronne** [coreos/coreos-installer#111]
# Feature Request #

I would like to have the possibility to download it as a binary from the releases page for the different linux architectures.

If it is not possible, maybe add it in a apt compatible repository for those who use Debian, Ubuntu, etc...

**Comment by lucab** [comment]
Thanks for the report. This is a recurring discussion among all the projects we maintain, but we don't have a coherent stance and we take ad-hoc decision per each project.

In this case, so far we settled on:
 * publishing sources on crates.io (this allows `cargo install`)
 * publishing a container image on quay.io (this allows running the binary on any environment with a container runtime)
 * encouraging distributors to package the released version from crates.io
 * NOT directly building and shipping binaries on our own (e.g. attached to GitHub)

Thus we are not going into covering all package formats here on our own. Feel free to point your preferred distribution to here for proper packaging. In the meanwhile, if you have a container runtime available in your environment, you can try using the image on quay.io.

**Comment by micheelengronne** [comment]
I have a container runtime in my env but I want to use coreos-installer in a provisioning container already. Container in container, I am not thrilled by that.

I will wait for an Ubuntu release (the distro I provision from).

**Comment by micheelengronne** [comment]
The same for https://github.com/coreos/fcct

**Comment by micheelengronne** [comment]
Can we keep this issue open until ubuntu packaging ? I rename it.

**Comment by lucab** [comment]
@micheelengronne if you are building/managing your provisioning container on your own, then you can also just `cargo install coreos-installer` when you are assembling the image (assuming Ubuntu has a recent enough `cargo` or `rustup`).

I'm fine with keeping this open, but please also forward it to a proper Ubuntu packaging request and cross-link it here.

**Comment by Patrick-Remy** [comment]
Since [v0.4.0](https://github.com/coreos/fcct/releases/tag/v0.4.0), fcct does provide prebuilt binaries. Is there a chance to get binaries for this repo as well?

In my scenario, I setup my infrastructure via [terraform](https://www.terraform.io) and boot into the available (debian-based) initramfs rescue mode. There I have only limited fs space available (~800MB for the smallest machine 2GB machine). I tried installing it with `cargo` or `podman`, but both approaches reach the file system limit. 

The current workaround is to build coreos-installer via `cargo` on a debian machine, copy the binary to the terraform host (if differ as in my case), and copy it via [file provisioner](https://www.terraform.io/docs/provisioners/file.html) to the cloud machine. This costs a lot of time to try all approaches, and can prevent more users from using Fedora CoreOS.

**Comment by bgilbert** [comment]
There are currently no plans to distribute bare binaries in the upstream repo.  We recommend running coreos-installer from the container image.

Your workaround sounds reasonable for your scenario, but your scenario sounds unusual to me.  What cloud provider are you using?  In cloud scenarios we generally recommend booting from an [official Fedora CoreOS image](https://getfedora.org/coreos/download?tab=cloud_operators&stream=stable), as coreos-installer is mostly intended for installing on bare metal.

**Comment by Patrick-Remy** [comment]
I am using [Hetzner Cloud](https://www.hetzner.de/cloud), and wrote a short tutorial: [Patrick-Remy/howto-fedora-coreos-hetzner-cloud](https://github.com/Patrick-Remy/howto-fedora-coreos-hetzner-cloud). I just found out, that there is a CoreOS *31* ISO available which can be used with terraform as an alternate way to install (and upgrade to 32 afterwards).

**Comment by bgilbert** [comment]
We'd welcome the addition of a coreos-installer package to Ubuntu or any other Linux distro.  We're unlikely to do it ourselves, though, so I'll go ahead and close this.  If anyone is building a coreos-installer package and would like advice or code review, please feel free to open an issue here or contact us in `#fedora-coreos` on Libera.Chat.
