### ISSUE TITLE
allow for `--ignition` to grab from a url; check before downloading disk

### ISSUE THREAD

**Issue by dustymabe** [coreos/coreos-installer#118]
Can we allow for ignition to be either a local file or a URL that can be retrieved? Right now it only accepts a local file. Would be nice if we can use either a local file or grab from a URL if a URL is specified.

Also can we verify we can grab the ignition config (from either local file or URL) before we try to download the disk image? I hit a case where the installer downloaded the disk image and then failed to locate the ignition config. It would have saved some bandwidth if we checked the ignition file first.

```
Downloading image from http://192.168.122.1:9000/fedora-coreos-31.20191220.dev.3-metal.x86_64.raw.gz
Downloading signature from http://192.168.122.1:9000/fedora-coreos-31.20191220.dev.3-metal.x86_64.raw.gz.sig
Signature fetch failed: 404 Not Found
Signature not found; skipping verification as requested
> Read disk 684.9 MiB/684.9 MiB (100%)   
Writing Ignition config
Error: opening source Ignition config http://192.168.122.1:8000/user-systemd.ign
Caused by: No such file or directory (os error 2)
Clearing partition table
Error: install failed
```

**Comment by dustymabe** [comment]
@jlebon, so you hit this too. Do you support the feature request?

**Comment by lucab** [comment]
My 2¢ on this: the second part of the ticket sounds fair, but I'm a bit wary on the first part (grab content from URL).

In particular, I think we are heading toward the usual spectrum of nuances around remote content (checking integrity, checking authenticity, endpoints behind authentication, cloud buckets, etc).
As we are now running in a real OS and those details change across usecases, I'd rather leave that part to the users so that they can range from a simple `curl` to more complex `podman run $downloader` stuff.

**Comment by jlebon** [comment]
> In particular, I think we are heading toward the usual spectrum of nuances around remote content (checking integrity, checking authenticity, endpoints behind authentication, cloud buckets, etc).

Hmm, I think at least supporting HTTP seems reasonable given that we already today support downloading disk images that way too. (In fact, when I ran into this, I was serving the image and the Ignition config via the same httpd thinking it would Just Work.)

I totally agree though we don't want to start expanding this much farther (just like we wouldn't for the disk images themselves). Plus, users can also leverage the Ignition fetcher too to download from e.g. S3 and tftp.

**Comment by jlebon** [comment]
https://github.com/coreos/coreos-installer/pull/126

**Comment by bgilbert** [comment]
I'm also wary of this for the reasons mentioned by @lucab .  The installer must support fetching images because we stream them directly to disk, but I intentionally omitted fetching of Ignition configs because (AFAIK) it doesn't actually need to be done within the installer.  Unix philosophy and all that.

**Comment by jlebon** [comment]
>  The installer must support fetching images because we stream them directly to disk, but I intentionally omitted fetching of Ignition configs because (AFAIK) it doesn't actually need to be done within the installer

Right, this is definitely not a need, though it's a surprising missing feature given the context of an installer. I think it's telling that at least two of the three/four people who played with the new installer fell in the trap. (Worth noting too the code in #126 does actually stream the Ignition config to disk as well. ;) )

**Comment by dustymabe** [comment]
> I'm also wary of this for the reasons mentioned by @lucab . The installer must support fetching images because we stream them directly to disk, but I intentionally omitted fetching of Ignition configs because (AFAIK) it doesn't actually need to be done within the installer. Unix philosophy and all that.

Based on your comment let's see if there are few holes in there :)

- We do support downloading ignition from a URL in the systemd service. I feel like an argument for doing it there is an argument for supporting it directly in the installer itself (more rust, less bash). So why is it good to support it in one place but not the other?
- Regarding unix philosophy; there are some really cool things `coreos-installer` does today that aren't striclty required by it. Should all of these useful, but possibly extraneous features be part of a separate tool or should we require the user to do it on their own?
    - downloading disk image from URL (could just operate on a file provided by the user)
    - GPG signature checking (could require the user to do that before calling the installer)
    - `coreos-installer iso` for embedding an ignition config in a Live ISO
    - `coreos-installer download` for talking to our metadata service and downloading an ISO

I think all of those mentioned features add value. 

I feel like I'm missing the point of your argument. Am I?

**Comment by bgilbert** [comment]
> So why is it good to support it in one place but not the other?

I'll call the Ignition config for the live PXE boot which executes the installer the "installer config", and the one for the installed system the "target config".

We need support in kargs because without an installer config, the user has no other way to fetch the target config into a file on the host system.  _With_ an installer config, the installer config itself should direct Ignition to fetch the target config.  That also allows use of Ignition's file validation features (SHA-512 or whatever might be added later).

When running from the command line, same situation: the user already has ways to fetch a remote file.

> downloading disk image from URL (could just operate on a file provided by the user)

Streaming fetch + install is core functionality of the installer for efficiency reasons.  We don't want to buffer the image to a slow USB boot device, nor to require hundreds of MB of additional RAM.

> GPG signature checking (could require the user to do that before calling the installer)

Needed for streaming.

> coreos-installer iso for embedding an ignition config in a Live ISO

Users without PXE servers want to automate installs using the ISO image, and there's no other way to avoid them having to type in kargs by hand.  Could be part of a separate tool, but it's convenient to have install-related functionality all in the same place.

> coreos-installer download for talking to our metadata service and downloading an ISO

Useful functionality that was basically free because the code already existed in coreos-installer, and which encapsulates some complexity the user would otherwise have to implement by hand.

> I feel like I'm missing the point of your argument. Am I?

I think so?  There's a utility/complexity tradeoff with any feature.  I don't think punting `wget` to the user is especially burdensome, and it avoids us getting into the business of checksumming/GPG-verifying user-provided data.  (Since the user would have no opportunity to do so between download and use.)

Would it be less confusing if the `-i` long option was called `--ignition-file` by analogy with `--image-file`?

Now, yes, we could provide simple fetching functionality, and the user could still do their own thing if they wanted integrity checking or fanciness.  If there's a strong consensus around adding the functionality, I can live with it.  It seems only unnecessary to me, where #117 feels actively wrong.

**Comment by dustymabe** [comment]
> When running from the command line, same situation: the user already has ways to fetch a remote file.

From a user interface perspective (i.e. typing on the command line) it seems like it would be much better if I have one or two less steps to take. Obviously this is my opinion.

> Now, yes, we could provide simple fetching functionality, and the user could still do their own thing if they wanted integrity checking or fanciness. If there's a strong consensus around adding the functionality, I can live with it.

Yeah I was thinking we could easily cover most use cases by allowing the user to specify a URL and a checksum. If they want to do signature checking then they can download it separately.

**Comment by miabbott** [comment]
Ran into this situation myself today thinking I could fetch the image and Ignition config from a URL when running the `coreos-installer` from the command line.

I'm in the camp of wanting to provide the `--ignition-url` option for users executing the installer on the command line as it seems to be complementary to `--image-url`.  However, I can understand some of the arguments for not wanting to implement that option as stated in comments above.

I think a happy medium would be to rename `--ignition` to `--ignition-file` and expand the help text to clarify that the argument expects a local file and no remote URLs are accepted.

**Comment by bgilbert** [comment]
I believe the consensus around this was to rename `--ignition` to `--ignition-file` and add `--ignition-url`.

**Comment by cgwalters** [comment]
Yep, when writing https://github.com/coreos/coreos-assembler/pull/1268 I ended up needing to synthesize a "pointer config".

**Comment by miabbott** [comment]
Can this be closed with https://github.com/coreos/coreos-installer/pull/173?

**Comment by jlebon** [comment]
Hmm, right I think now I can rebase https://github.com/coreos/coreos-installer/pull/126 on top of the latest and rename it `--ignition-url`.
