### ISSUE TITLE
OCP4.2 Install: can the coreos.inst.install_dev values updated with multiple disks to extend the /sysroot

### ISSUE THREAD

**Issue by AnitaNayak** [coreos/coreos-installer#129]
The nodes have multiple disks. But OCP 4.2 takes only one disk as param in `coreos.inst.install_dev`. Can the `coreos.inst.install_dev` value be updated with multiple disks to extend the /sysroot in all.yaml file.

## Host Operating System Version ## 
Red Hat Enterprise Linux release 8.1 (Ootpa)
## Target Operating System Version ## 
Red Hat Enterprise Linux release 8.1 (Ootpa)

## coreos-installer Version ## 
Red Hat Enterprise Linux CoreOS release 4.2

**Comment by lucab** [comment]
I *think* that what you are asking is not possible, as the sysroot has to be on a single disk.
But I may have misunderstood your scenario or other OCP-specific details (e.g. I am not sure what `all.yaml` is).

Please report this (and any other OCP bugs) to https://bugzilla.redhat.com/ in order to get better assistance. I'm closing this here, but we can followup if it turns out to be a reasonable missing feature.
