### ISSUE TITLE
Installing CoreOS on Intel VROC RAID1 leaves array in degraded state

### ISSUE THREAD

**Issue by miabbott** [coreos/coreos-installer#179]
(Manually imported from https://github.com/openshift/os/issues/401)

**Version**
Openshift 4.2 and 4.3

**Platform:**
baremetal

**What happened?**
After the installer is launched with rd.md=1 rd.auto coreos.inst.install_dev=md126 (where md126 is a reference to /dev/md126, which is an assembled VROC RAID1 array), the OS ends up installed, but the whole process leaves the array in degraded state. This leaves the system boostrapped not the way that was intended (with redundancy).

**What you expected to happen?**
Installation on /dev/md126 to succeed properly without degrading the array. Maybe there's a special way to install CoreOS that way or modify the standard wipefs+dd behaviour?

**How to reproduce it (as minimally and precisely as possible)?**
Assemble an Intel VROC RAID1 array and install to the resultant MD device (e.g. /dev/md126) with parameters provided above.

**Anything else we need to know?**
Most probably this is due to how the installation process is handled. Possibly due to wipefs being launched, which kills the metadata on partition, and afterwards being overwritten with dd. I would probably investigate modifying the Ignition files manually, but I'd rather not delve into monkey patching myself.

cc: @Feelas

**Comment by Feelas** [comment]
I'd like to add that the degradation might also happen during update, as I had an installation succeed before and array got degraded after updating from one RHCOS version to another.

**Comment by a1bokhari** [comment]
This issue is also seen while installing CoreOS (OCP 4.3) on a Supermicro (supersaver 1028-TDW) server with software RAID. The RAID-1 config is broken after the installation. 

[core@worker-2 ~]$ lsblk
NAME                         MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
sda                            8:0    0 931.5G  0 disk  
├─sda1                         8:1    0   384M  0 part  /boot
├─sda2                         8:2    0   127M  0 part  /boot/efi
├─sda3                         8:3    0     1M  0 part  
└─sda4                         8:4    0   931G  0 part  
  └─coreos-luks-root-nocrypt 253:0    0   931G  0 dm    /sysroot
sdb                            8:16   0 931.5G  0 disk  
└─md126                        9:126  0 884.9G  0 raid1 
  ├─md126p1                  259:0    0     1G  0 md    
  └─md126p2                  259:1    0 883.9G  0 md    
    ├─rhel_worker--2-swap    253:1    0     4G  0 lvm   
    ├─rhel_worker--2-home    253:2    0 829.9G  0 lvm   
    └─rhel_worker--2-root    253:3    0    50G  0 lvm   
sr0                           11:0    1  1024M  0 rom   

[root@worker-2 ~]# cat /proc/mdstat
Personalities : [raid1] 
md126 : active raid1 sdb[0]
      927881216 blocks super external:/md127/0 [2/1] [_U]
      
md127 : inactive sdb[0](S)
      5201 blocks super external:imsm
       
unused devices: <none>
[root@worker-2 ~]#

**Comment by made-with-care** [comment]
Same problem.
Any WA or progress?

**Comment by bgilbert** [comment]
This particular bug applies to the legacy coreos-installer shipped with OCP < 4.6 and never shipped with Fedora CoreOS.  However, both Fedora CoreOS and RHEL CoreOS now natively support mirroring the boot disk.  For FCOS, see [this example](https://coreos.github.io/butane/examples/#mirrored-boot-disk) and the last example in [this section](https://docs.fedoraproject.org/en-US/fedora-coreos/storage/#_reconfiguring_the_root_filesystem).  For RHCOS, see [these instructions](https://docs.openshift.com/container-platform/4.7/installing/install_config/installing-customizing.html#installation-special-config-mirrored-disk_installing-customizing).

Since software RAID of the boot disk is now officially supported, and FakeRAID support will not be added to the legacy installer, I'll close.
