### ISSUE TITLE
Different ways to handle ignition configs

### ISSUE THREAD

**Issue by dustymabe** [coreos/coreos-installer#3]
1.  provide `coreos.inst.ignition_url` on installer cmdline and embed it in the installed disks boot partition (what happens today)
2. provide `coreos.inst.ignition_url` and expect it to be grabbed by ignition during first boot. Allows for ignition config to be created/modified later or dynamically generated at runtime when request comes in. Could add another command line switch for this maybe. 
3. Complete offline mode: allow for ignition config to be provided via the ISO or via local disk?

**Comment by smekkley** [comment]
What is the motive for the second one?
Matchbox returns dynamic response against the "same" endpoint.

In the profiles/, you'd have a json file with the following entry for args.
coreos.inst.ignition_url=http://10.0.0.1/ignition?uuid=${uuid}&mac=${mac:hexhyp}

In the groups/, you'd have a json file with selector entry based on mac address. and define variables.

In the ignition/, you'd put a template yaml file with variables of the ignition.(not json, because matchbox automatically handles it)

At this point, matchbox doesn't support ignition ver3. But it'll be minor patch for them to support it.

**Comment by imranrazakhan** [comment]
@dustymabe is third option"Complete offline mode: allow for ignition config to be provided via the ISO or via local disk?" available now?

**Comment by bgilbert** [comment]
The third option is now handled by the ISO/PXE customization infrastructure, and the second one is covered by #158.  Closing this out.
