### ISSUE TITLE
Consider adding subcommand to wrap an Ignition config in an initrd for appending

### ISSUE THREAD

**Issue by bgilbert** [coreos/coreos-installer#322]
# Feature Request #

## Desired Feature ##

The Ignition Dracut glue knows how to pull a user config from an appended initrd.  (See bullet 4 [here](https://docs.fedoraproject.org/en-US/fedora-coreos/migrate-cl/#_operator_notes)).  The process of constructing a compatible cpio.gz is clunky from the command line, but would be trivial as a coreos-installer subcommand.

## Other Information ##

This could be useful for some PXE use cases, notably bootstrapping a custom TLS CA via an HTTPS fetch by an iPXE config that already trusts that CA.

**Comment by jlebon** [comment]
> This could be useful for some PXE use cases, notably bootstrapping a custom TLS CA via an HTTPS fetch by an iPXE config that already trusts that CA.

On that topic, I wonder if we should have a similar `ignition.config.hash` to go alongside `ignition.config.url`. If provided, we ignore invalid/missing certificates (but fail if hashes don't match).

I don't think it fully obviates the feature request here, because just trusting the CA from the start is a more generic fix than e.g. having to possibly tweak PXE configs per-node. But still, it might be more convenient in some situations.

**Comment by bgilbert** [comment]
PR in https://github.com/coreos/coreos-installer/pull/344.
