### ISSUE TITLE
ci: missing multi-arch jobs

### ISSUE THREAD

**Issue by lucab** [coreos/coreos-installer#424]
We used to have `s390x` CI runs on Travis, however it is not working anymore and https://github.com/coreos/coreos-installer/pull/423 dropped it. As GitHub runners are `x86_64` only, this unfortunately means we don't have anymore coverage for other production arches (`s390x`, `ppc64le` and `aarch64`).

**Comment by bgilbert** [comment]
https://github.com/coreos/coreos-installer/pull/734 added s390x coverage via emulation.  Since that's relatively compute-intensive, and aarch64/ppc64le are similar to x86_64 for our purposes, we didn't add coverage for those.  We do get some coverage via OS kola tests on aarch64/ppc64le builders, though of course we only get that _after_ an upstream release.

I'll go ahead and close this.  If we decide to add aarch64/ppc64le later, we can do so easily by reusing the s390x wrapper code.
