### ISSUE TITLE
Provide precompiled static binaries

### ISSUE THREAD

**Issue by 1player** [coreos/coreos-installer#965]
Running `coreos-installer` under podman is not always feasible, and it would help immensely if I could download a precompiled binary of coreos-installer, without having to compile it manually myself.

**Comment by bgilbert** [comment]
coreos-installer depends on some external programs as well as external libraries.  It would be possible to document a list of requirements, but the nice thing about the container image is that we can avoid all that.  Could you give some more detail about your use case that won't work with the container image?

**Comment by 1player** [comment]
I'm trying to install it on Hetzner Cloud, and there's no way of installing the ISO or using any of the precompiled images (because they support a limited number of archive extensions).

They have a rescue system running on Debian 11, but that distro ships with too old a rust to compile coreos-installer, and too old a glibc to compile on a modern Fedora machine and scp over. So the only solution to install CoreOS on Hetzner was rigging up a debian 11 container on my machine, compiling coreos-installer and scp'ing it over.

A precompiled binary ready for download would have saved me 1 hour and a half.

**Comment by bgilbert** [comment]
Okay, makes sense.  Thanks for the additional info.  While it's possible to install CoreOS on unsupported clouds by using the bare-metal install flow, it's not recommended, and I don't think we can prioritize support for arbitrary rescue images on unsupported cloud vendors.  I'll close this for now, but please consider [requesting Hetzner Cloud support](https://github.com/coreos/fedora-coreos-tracker/issues/new/choose) in the Fedora CoreOS tracker, and/or using a supported cloud provider.

**Comment by 1player** [comment]
Just to clarify, running CoreOS outside of the blessed cloud vendors is considered unsupported?

**Comment by bgilbert** [comment]
FCOS supports bare metal, but does not support cloud providers or virtualization systems that don't have official FCOS images.  Fedora is free software and of course you're free to do whatever you want with it, including using the bare metal install flow in unsupported environments.  But we don't test on those platforms, may not provide full functionality there (e.g. fetching SSH keys from the platform metadata service), and are unlikely to prioritize fixing issues that only occur on those platforms.

We do already ship static binaries for ignition-validate and Butane, and it'd be nice to avoid that additional maintenance burden here.  In this case, even if we shipped separate binaries, we'd continue to recommend the container image because it encapsulates dependencies better.  As a result, the separate binaries would mostly be used in unusual environments that we don't have easy access to, increasing the chances that the binary doesn't actually work.
